#!/bin/sh

DIR=$HOME/tmp
DEV_PROFILE=dev-profile
DEV_PROFILE_BACKUP=$DEV_PROFILE.tar.gz
BROWSER="chromium-browser --auto-open-devtools-for-tabs"
CMD=$(basename $0)

# Start fresh
function startFresh() {
  echo "restoring saved profile and launching browser..."
  rm -rf $DEV_PROFILE
  [ -f $DEV_PROFILE_BACKUP ] && tar xf $DEV_PROFILE_BACKUP -C $HOME/tmp
  $BROWSER --user-data-dir=$DEV_PROFILE #--disable-web-security
}

# Save current profile
function saveProfile() {
  echo "saving current profile..."
  [ -f $DEV_PROFILE_BACKUP ] && mv $DEV_PROFILE_BACKUP $DIR/old.tar.gz
  tar zcf $DEV_PROFILE_BACKUP $DEV_PROFILE
}

# Run without resetting profile:
function keep() {
  echo "launching with saved profile..."
  $BROWSER --user-data-dir=$DEV_PROFILE #--disable-web-security
}

cd $DIR

case "$1" in
  help) echo -e "Usage:\n\
  $CMD    restore saved profile and start browser\n\n\
  $CMD [keep|save|help]\n\n\
  keep    use last version (don't reset profile)\n\
  save    save current profile\n\
  help    show this help";;
  keep) keep ;;
  save) saveProfile ;;
  *) startFresh ;;
esac
