#!/bin/sh

# script:
#   nginx temporal server
#
# description:
#   This script runs a "production" server with
#   no special configuration in a docker container
#   and destroys the container when done.
#
# author:
#   juboba <juboba@gmail.com>
#
# usage:
#   nginx [directory] [port]

PORT=${2:-9009}
ROOT_DIR=$(pwd)

[ -n "$1" ] && ROOT_DIR="$ROOT_DIR/$1"

echo "Serving dir $ROOT_DIR with nginx on port $PORT"

docker run --rm -p $PORT:80 -v $ROOT_DIR:/usr/share/nginx/html nginx
