#!/bin/sh

FILE=$(rg --files 2> /dev/null \
  | sed -e "s/\(.*\)\/.*$/\1/" \
  | sort \
  | uniq \
  | rofi -dmenu -matching fuzzy -p 'Open with Sxiv' -sort -levenshtein-sort)

echo $FILE

if [ -n "$FILE" ] ; then
  sxiv -t $FILE;
fi
