#!/bin/sh

DEVICES=$(pacmd list-sinks | grep -E 'index:|name:')
# load-module module-stream-restore restore_device=false
# pacmd set-default-sink

# Script taken from:
# https://askubuntu.com/questions/71863/how-to-change-pulseaudio-sink-with-pacmd-set-default-sink-during-playback

case "${1:-}" in
  ""|list)
    pacmd list-sinks |
      grep -E 'index:|name:'
    ;;
  "t")
    index=$(sndsel | grep index | grep -v \* | sed -e 's/^[ \t]*//' | cut -d' ' -f2)
    name=$(sndsel | grep "index: $index" -A 1 | grep name | sed 's/.*<alsa_output\.[a-z]\{3\}-\(.*\)\.analog-stereo>/\1/')
    echo "Switching to: [$index] $name..."
    sndsel $index > /dev/null
    ;;
  [0-9]*)
    echo switching default
    pacmd set-default-sink $1 ||
      echo failed
    echo switching applications
    pacmd list-sink-inputs |
      awk '/index:/{print $2}' |
      xargs -r -I{} pacmd move-sink-input {} $1 ||
        echo failed
    ;;
  *)
    echo "Usage: $0 [|list|<sink name to switch to>]"
    ;;
esac

#echo $DEVICES

# select device in $DEVICES
# do
#   echo $device
# done
