#!/bin/sh
CMD=$(basename $0)
YEELIGHT_SCRIPTS="$HOME/Repositories/yeelight-shell-scripts"

action() {
  case $1 in
    "b") $YEELIGHT_SCRIPTS/yeelight-brightness.sh $2 $3 ;;
    "t") $YEELIGHT_SCRIPTS/yeelight-colortemp.sh $2 $3 ;;
    "c") $YEELIGHT_SCRIPTS/yeelight-rgb.sh $2 $3 ;;
    "s") $YEELIGHT_SCRIPTS/yeelight-scene.sh $2 $3 $4;;
    "o") $YEELIGHT_SCRIPTS/yeelight-toggle.sh $2 ;;
    *) show_help ;;
  esac
}

show_help() {
  echo -e "Usage: \n\
    $CMD LAMP ACTION  \n\
    Lamps:
      master, child, living, all
    Actions:
    b    for brightness: $CMD b [0-100]\n\
    t    for color temperature: yee t 1700\n\
    c    for color: $CMD c [0-255],[0-255],[0-255]\n\
    s    for scene: $CMD s [Option]\n\
    o    to toggle on/off: yee o"
}

case $1 in
  "master") action $2 1 $3 ;;
  "child") action $2 2 $3 ;;
  "living") action $2 3 $3
            action $2 4 $3 ;;
  "all") action $2 0 $3 ;;
  *) show_help ;;
esac
